# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setBaseSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(169, 169, 169);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appFrame = QtWidgets.QFrame(self.centralwidget)
        self.appFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appFrame.setObjectName("appFrame")
        self.headingFrame = QtWidgets.QFrame(self.appFrame)
        self.headingFrame.setGeometry(QtCore.QRect(0, 0, 1281, 81))
        self.headingFrame.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.headingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headingFrame.setObjectName("headingFrame")
        self.labelOPCUA = QtWidgets.QLabel(self.headingFrame)
        self.labelOPCUA.setGeometry(QtCore.QRect(360, 10, 611, 61))
        self.labelOPCUA.setStyleSheet("color: rgb(43, 100, 173);\n"
                                      "font: 35pt \"Roboto\";")
        self.labelOPCUA.setTextFormat(QtCore.Qt.AutoText)
        self.labelOPCUA.setScaledContents(False)
        self.labelOPCUA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOPCUA.setObjectName("labelOPCUA")
        self.logoSMC = QtWidgets.QLabel(self.headingFrame)
        self.logoSMC.setGeometry(QtCore.QRect(10, 10, 191, 61))
        self.logoSMC.setText("")
        self.logoSMC.setTextFormat(QtCore.Qt.RichText)
        self.logoSMC.setPixmap(QtGui.QPixmap("OpcUaClient_mainwindowUI/icones_for_gui/smc_logo.png"))
        self.logoSMC.setScaledContents(True)
        self.logoSMC.setObjectName("logoSMC")
        self.connectivityFrame = QtWidgets.QFrame(self.appFrame)
        self.connectivityFrame.setGeometry(QtCore.QRect(450, 90, 231, 80))
        self.connectivityFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectivityFrame.setObjectName("connectivityFrame")
        self.connectButton = QtWidgets.QPushButton(self.connectivityFrame)
        self.connectButton.setGeometry(QtCore.QRect(120, 0, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                        "font: 11pt \"Roboto\";\n"
                                        "color: rgb(43, 100, 173);\n")
        self.connectButton.setCheckable(False)
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.connectivityFrame)
        self.disconnectButton.setGeometry(QtCore.QRect(120, 42, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectButton.sizePolicy().hasHeightForWidth())
        self.disconnectButton.setSizePolicy(sizePolicy)
        self.disconnectButton.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                            "font: 11pt \"Roboto\";\n"
                                            "color: rgb(43, 100, 173);\n")
        self.disconnectButton.setCheckable(False)
        self.disconnectButton.setObjectName("disconnectButton")
        self.aksEndpoints = QtWidgets.QPushButton(self.connectivityFrame)
        self.aksEndpoints.setGeometry(QtCore.QRect(10, 0, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aksEndpoints.sizePolicy().hasHeightForWidth())
        self.aksEndpoints.setSizePolicy(sizePolicy)
        self.aksEndpoints.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                        "font: 11pt \"Roboto\";\n"
                                        "color: rgb(43, 100, 173);\n")
        self.aksEndpoints.setCheckable(False)
        self.aksEndpoints.setFlat(False)
        self.aksEndpoints.setObjectName("aksEndpoints")
        self.connectivityIcon = QtWidgets.QLabel(self.connectivityFrame)
        self.connectivityIcon.setGeometry(QtCore.QRect(32, 31, 55, 55))
        self.connectivityIcon.setText("")
        self.connectivityIcon.setTextFormat(QtCore.Qt.RichText)
        self.connectivityIcon.setPixmap(QtGui.QPixmap("OpcUaClient_mainwindowUI/icones_for_gui/disconected1.png"))
        self.connectivityIcon.setScaledContents(True)
        self.connectivityIcon.setObjectName("connectivityIcon")
        self.statusBar = QtWidgets.QPlainTextEdit(self.appFrame)
        self.statusBar.setGeometry(QtCore.QRect(10, 640, 511, 71))
        self.statusBar.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                     "font: 11pt \"Roboto\";\n"
                                     "color: rgb(43, 100, 173);")
        self.statusBar.setReadOnly(True)
        self.statusBar.setObjectName("statusBar")
        self.URIFrame = QtWidgets.QFrame(self.appFrame)
        self.URIFrame.setGeometry(QtCore.QRect(10, 90, 441, 80))
        self.URIFrame.setObjectName("URIFrame")
        self.serverURI = QtWidgets.QLineEdit(self.URIFrame)
        self.serverURI.setGeometry(QtCore.QRect(130, 0, 301, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverURI.sizePolicy().hasHeightForWidth())
        self.serverURI.setSizePolicy(sizePolicy)
        self.serverURI.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                     "font: 11pt \"Roboto\";\n"
                                     "color: rgb(43, 100, 173);")
        self.serverURI.setObjectName("serverURI")
        self.connectLabel = QtWidgets.QLabel(self.URIFrame)
        self.connectLabel.setGeometry(QtCore.QRect(0, 0, 131, 31))
        self.connectLabel.setStyleSheet("font: 11pt \"Roboto\";\n"
                                        "color: rgb(43, 100, 173);")
        self.connectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectLabel.setObjectName("connectLabel")
        self.mainFrame = QtWidgets.QFrame(self.appFrame)
        self.mainFrame.setGeometry(QtCore.QRect(10, 170, 1271, 461))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.dataChangeUI = QtWidgets.QTableView(self.mainFrame)
        self.dataChangeUI.setGeometry(QtCore.QRect(520, 0, 741, 461))
        self.dataChangeUI.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                        "font: 11pt \"Roboto\";\n"
                                        "color: rgb(43, 100, 173);")
        self.dataChangeUI.setObjectName("dataChangeUI")
        self.dataChangeUI.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.browserUI = QtWidgets.QTreeView(self.mainFrame)
        self.browserUI.setGeometry(QtCore.QRect(0, 0, 511, 461))
        self.browserUI.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                     "font: 11pt \"Roboto\";\n"
                                     "color: rgb(43, 100, 173);")
        self.browserUI.setObjectName("browserUI")
        self.browserUI.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.QueryFrame = QtWidgets.QFrame(self.appFrame)
        self.QueryFrame.setGeometry(QtCore.QRect(870, 80, 401, 91))
        self.QueryFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.QueryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QueryFrame.setObjectName("QueryFrame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.QueryFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 5, 131, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.label_1.setStyleSheet("font: 11pt \"Roboto\";\n"
                                   "color: rgb(43, 100, 173);")
        self.verticalLayout_2.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("font: 11pt \"Roboto\";\n"
                                   "color: rgb(43, 100, 173);")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("font: 11pt \"Roboto\";\n"
                                   "color: rgb(43, 100, 173);")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.QueryFrame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 5, 271, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_1.setEnabled(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_1.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                     "font: 11pt \"Roboto\";\n"
                                     "color: rgb(43, 100, 173);")
        self.lineEdit_1.setReadOnly(True)
        self.verticalLayout_3.addWidget(self.lineEdit_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                     "font: 11pt \"Roboto\";\n"
                                     "color: rgb(43, 100, 173);")
        self.lineEdit_2.setReadOnly(True)
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setStyleSheet("background-color: rgb(235, 235, 235);\n"
                                     "font: 11pt \"Roboto\";\n"
                                     "color: rgb(43, 100, 173);")
        self.lineEdit_3.setReadOnly(True)
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addWidget(self.appFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelOPCUA.setText(_translate("MainWindow", "OPC Unified Architecture Klient"))
        self.connectButton.setText(_translate("MainWindow", "Připojit"))
        self.disconnectButton.setText(_translate("MainWindow", "Odpojit"))
        self.aksEndpoints.setText(_translate("MainWindow", "Dotaz serveru"))
        self.serverURI.setText(_translate("MainWindow", "opc.tcp://opcuaserver.com:48010"))
        self.connectLabel.setText(_translate("MainWindow", "Připojení k serveru:"))
        self.label_1.setText(_translate("MainWindow", "(SecurityMode):"))
        self.label_2.setText(_translate("MainWindow", "(SecurityPolicy):"))
        self.label_3.setText(_translate("MainWindow", "(None):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
